-- MySQL Script generated by MySQL Workbench
-- Wed Nov  4 19:19:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_shop` DEFAULT CHARACTER SET utf8 ;
USE `online_shop` ;

-- -----------------------------------------------------
-- Table `online_shop`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `mobile` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_Users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` FLOAT NOT NULL,
  `discount` FLOAT NULL,
  `buyer_id` INT NULL,
  `shipping_address` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sales_Users1_idx` (`buyer_id` ASC) VISIBLE,
  INDEX `fk_Orders_Addresses1_idx` (`shipping_address` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Users1`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Addresses1`
    FOREIGN KEY (`shipping_address`)
    REFERENCES `online_shop`.`Addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Order_Items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Products_has_Orders_Orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_Products_has_Orders_Products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_items_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_items_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_shop`.`Orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_method` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `order_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transactions_Orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Transactions_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `online_shop`.`Orders` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Product_Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Product_Reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Reviews_Products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Reviews_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Product_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Product_Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_Categories_has_Products_Products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Products_Categories1_idx` (`category_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Product_Categories_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_shop`.`Categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Categories_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Gift_Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Gift_Cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NOT NULL,
  `user_id` INT NOT NULL,
  `code` VARCHAR(16) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gift_Cards_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Gift_Cards_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_verification_value` INT NOT NULL,
  `bank` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `cardholder_name` VARCHAR(45) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Card_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Card_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `readed` TINYINT(1) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Notifications_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notifications_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Search_Histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Search_Histories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(6) NOT NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_Products_has_SearchHistory_Products1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_Search_Histories_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Products_has_SearchHistory_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Search_Histories_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Favorites_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Favorites_Products1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Favorites_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `online_shop`.`Products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_shop`.`Preferences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_shop`.`Preferences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Preferences_Users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_Preferences_Categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Preferences_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `online_shop`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preferences_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `online_shop`.`Categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
